version: '3.8'

services:
  pd-redis:
    image: redis:alpine                 
    container_name: plate_detector_redis
    restart: always                     
    ports:
      - "6379:6379"                     

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: es01
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=12345
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - esdata01:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.4
    container_name: kib01
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjpNRVMzZF9CaFJWV2w5WGc1T1ZKV05n
    ports:
      - "5601:5601"

  pd-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: plate_detector_sql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=GucluBirSifre123!
    ports:
      - "1433:1433"
  
  api:
    build:
      context: ..
      dockerfile: PD.UI/Dockerfile
    container_name: myapi
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - pd-sql
      - pd-redis
      - elasticsearch
volumes:
 esdata01: